export const locale_list = ["en"];
export const default_locale = "en";
export const author = "Author";
export const website_url = "https://www.example.com";
export const organization_name = "Organization Name";
export const organization_logo = "https://www.example.com/logo.png";
export const default_title = "Boilerplate";
export const default_description = "Boilerplate description";
export const default_keywords = "boilerplate, keywords";